platform:
  - x86
  - x64
  
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    
matrix:
  exclude:
    - PYTHON: "C:\\Python36-x64"
      platform: x86
    - PYTHON: "C:\\Python37-x64"
      platform: x86
    
install:
  - "%PYTHON%\\python setup.py develop"
  - "%PYTHON%\\python.exe -m pip install -r %APPVEYOR_BUILD_FOLDER%\\requirements.txt"

# Not a .NET project, we build in the install step instead
build: false

test_script:
#  - ciocheck setup.py --disable-tests
#  - ciocheck pyswmm --disable-tests
  - "%PYTHON%\\Scripts\\pytest pyswmm"
#  - coveralls --disable-tests
